### ISSUE TITLE
Docs claim `id` attribute can be user-provided

### ISSUE THREAD

**Issue by qcxrvb** [OJFord/terraform-provider-wireguard#8]
Hi, i am working on a script which is supposed to generate both server and client configurations including private and public keys for all my users. I have a list of users and just in case i am going to remove a user in the future, i am trying to setup a custom id for each key:
```
resource "wireguard_asymmetric_key" "vpn_client" {
  count = length(local.permitted_clients)
  id    = sha256(local.permitted_clients[count.index].name)
}
```
This however produced the following error:
```
│ Error: Invalid or unknown key
│ 
│   with wireguard_asymmetric_key.vpn_client,
│   on private-key.tf line 6, in resource "wireguard_asymmetric_key" "vpn_client":
│    6:   id    = sha256(local.permitted_clients[count.index].name)
```
Can you please make the ID configurable?
The docs already say that this should be possible, but i think it is missing the required implementation ... 

Anyway, thank you very much for your effort to implement this provider :D

**Comment by OJFord** [comment]
I'm afraid this is an error in the docs: hashicorp/terraform-plugin-docs#45. `id` is never set explicitly in Terraform.

In your case I would suggest something like this:
```hcl
resource "wireguard_asymmetric_key" "vpn_client" {
  for_each = toset([for pc in local.permitted_clients : pc.name])
}
```

Which won't affect the `id`, but will mean the resources are indexed by client `name` (rather than the count index in your example).

This has the added benefit that removing a client 'in the middle' doesn't recreate all the other clients after it to shift them down one. In general, prefer `for_each` to `count`; the latter's only really useful if it's a bunch of homogenous copies - and even then there's nothing _wrong_ with `for_each`.

Sorry about the docs. I'm hoping `tfplugindocs` will see some progress soon.

**Comment by OJFord** [comment]
In fact I'll leave this open to track hashicorp/terraform-plugin-docs#45; partly so I don't get confused when it updates and removes the attr, and can close this then.

Thanks for bringing it to my attention - I hadn't noticed!
